require "open3"

require "machine_maker/counter"
require "machine_maker/commander_variable"
require "machine_maker/dimacs_writer"
require "machine_maker/certificate_decoder"
require "machine_maker/sat_solver"
require "machine_maker/configuration_reducer"
require "machine_maker/description_reducer"
require "machine_maker/step_reducer"
require "machine_maker/connection_reducer"
require "machine_maker/computation_reducer"
require "machine_maker/less_than"
require "machine_maker/symmetry_breaker"
